console.log("我是标题1");
var a = 20;
var b = 30;
console.log(b);
var c = "hello,man";
console.log(c);
var d = [1,2,3,4,5];
console.log(d);
console.log("我是最新的修改");
console.log("我是test02的修改");
console.log("我是test03的修改");
console.log("主分支第一次修改");
console.log("主分支第二次修改");
console.log("我是rebase分支的第一次修改");
console.log("我是rebase分支的第二次修改");
